Repository operate-first/odh-manifests, pull requests merged in 2022-04, with the labels that each got.

#10 Include BYON feature for jupyterhub component
  jupyterhub/byon/kustomization.yaml
  odh-dashboard/base/deployment.yaml
  odh-dashboard/base/role.yaml
Labels: size/M, lgtm

#14 statisfy kfdef with base directory
  jupyterhub/byon/base/kustomization.yaml
Labels: size/XS

#15 Updated the odh-dashboard manifests based on odh-dashboard
  odh-dashboard/base/cluster-role-binding.yaml
  odh-dashboard/base/deployment.yaml
  odh-dashboard/base/role.yaml
  odh-dashboard/base/service.yaml
Labels: size/M, lgtm

#13 add Reloader annotations to trino-coordinator deployment in osc-cl2
  trino/base/trino-coordinator-dc.yaml
  trino/base/trino-worker-dc.yaml
Labels: size/XS, lgtm

#17 Update trino to 373.
  trino/base/kustomization.yaml
Labels: size/XS

#16 Update trino to 373.
  trino/base/kustomization.yaml
Labels: size/XS

#19 [BYON] Cherry-pick pipelines into odh-manifests
  jupyterhub/byon/base/kustomization.yaml
  jupyterhub/jupyterhub/overlays/byon/byon-import-jupyterhub-image.yaml
  jupyterhub/jupyterhub/overlays/byon/byon-validate-jupyterhub-image.yaml
  jupyterhub/jupyterhub/overlays/byon/kustomization.yaml
Labels: size/L
