Repository operate-first/odh-manifests, pull requests merged in 2022-11, with the labels that each got.

#45 Update the dev version of the CNBi dashboard
  odh-dashboard/base/kustomization.yaml
Labels: size/XS, lgtm

#46 Update OWNERS of the CNBi / BYON dev env
  OWNERS
Labels: size/S, lgtm

#49 Clean up the content of odh-dashboard
  odh-dashboard/overlays/odhdashboardconfig/kustomization.yaml
Labels: size/XS, approved, lgtm
