Repository operate-first/odh-manifests, pull requests merged in 2022-12, with the labels that each got.

#51 Add role for CNBi access from the ODH dashboard in OSC cl1
  odh-dashboard/base/role.yaml
Labels: approved, size/S, lgtm

#50 add LF folks to owners
  OWNERS
Labels: size/XS, lgtm

#52 Update the CNBi version of the odh dashboard to v0.2.0
  odh-dashboard/base/kustomization.yaml
Labels: size/XS, approved, lgtm
