Repository operate-first/odh-manifests, pull requests merged in 2022-10, with the labels that each got.

#38 upgrade trino to 398
  trino/base/kustomization.yaml
Labels: size/XS

#39 Update how monitoring config is managed in trino.
  trino/base/kustomization.yaml
  trino/base/trino-coordinator-dc.yaml
  trino/base/trino-worker-dc.yaml
Labels: size/S

#40 [odh-cl1] Deploy the current dev version of the odh-dashboard
  odh-dashboard/base/deployment.yaml
Labels: size/XS, lgtm

#41 Update odh-dashboard to newest version above v2.2.1
  odh-dashboard/base/cluster-monitoring-role-binding.yaml
  odh-dashboard/base/cluster-role.yaml
  odh-dashboard/base/deployment.yaml
  odh-dashboard/base/kustomization.yaml
  odh-dashboard/base/odh-dashboard-crd.yaml
  odh-dashboard/base/role.yaml
  odh-dashboard/base/service.yaml
  odh-dashboard/overlays/authentication/deployment.yaml
  odh-dashboard/overlays/authentication/kustomization.yaml
  odh-dashboard/overlays/authentication/secret.yaml
  odh-dashboard/overlays/odhdashboardconfig/kustomization.yaml
  odh-dashboard/overlays/odhdashboardconfig/odh-dashboard-config.yaml
  odh-dashboard/overlays/odhdashboardconfig/odh-enabled-applications-config.configmap.yaml
Labels: size/L

#42 [osc-cl1-byon] Point the dashboard to the odh-admin group
  odh-dashboard/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Labels: size/XS, lgtm
